version: 2

sources:
  - name: olist_raw
    description: Raw data from Brazilian ecommerce platform Olist
    schema: RAW
    tables:
      - name: customers
 
      - name: orders
        loaded_at_field: order_purchase_timestamp
        freshness:
          warn_after:
            count: 2600
            period: day
          error_after:
            count: 2700
            period: day
 
      - name: order_items
      - name: products
      - name: payments